project:
  type: website
  output-dir: docs

website:
  title: "Danielle Ferraro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: styles.scss
    #css: styles.css
    mainfont: Work Sans
    toc: true
    page-layout: full

editor: visual

